# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting Started'
  link: '/getting-started'
- label: Layouts
  items:
    - label: 'Grid'
      link: '/layouts/grid'
    - label: 'Flex'
      link: '/layouts/flex'
    - label: 'Show'
      link: '/layouts/show'
    - label: 'Hide'
      link: '/layouts/hide'
- label: Components
  items:
    - label: 'Accordion'
      link: '/components/accordion'
    - label: 'Alert'
      link: '/components/alert'
    - label: 'Badge'
      link: '/components/badge'
    - label: 'Button'
      link: '/components/button'
    - label: 'Button Group'
      link: '/components/button-group'
    - label: 'Card'
      link: '/components/card'
    - label: 'Carousel'
      link: '/components/carousel'
    - label: 'Collapse'
      link: '/components/collapse'
    - label: 'Dropdown'
      link: '/components/dropdown'   
    - label: 'Header'
      link: '/components/header' 
    - label: 'Input'
      link: '/components/input'
    - label: 'List'
      link: '/components/list'
    - label: 'Modal'
      link: '/components/modal'
    - label: 'Navbar'
      link: '/components/navbar'
    - label: 'Toolbar'
      link: '/components/toolbar'  
- label: Support
  items:
    - label: 'Buy Me Coffee ❤️'
      link: https://github.com/bothelljs
    - label: 'Star On Github ⭐'
      link: https://github.com/bothelljs
