# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Layout
  items:
    - label: 'Grid'
      link: '/layout/grid'
    - label: 'Flex'
      link: '/layout/flex'
    - label: 'Show'
      link: '/layout/show'
    - label: 'Hide'
      link: '/layout/hide'
- label: Components
  items:
    - label: 'Accordion'
      link: '/component/accordion'
    - label: 'Alert'
      link: '/component/alert'
    - label: 'Badge'
      link: '/component/badge'
    - label: 'Button'
      link: '/component/button'
    - label: 'Button Group'
      link: '/component/button-group'
    - label: 'Card'
      link: '/component/card'
    - label: 'Carousel'
      link: '/component/carousel'
    - label: 'Collapse'
      link: '/component/collapse'
    - label: 'Dropdown'
      link: '/component/dropdown'   
    - label: 'Header'
      link: '/component/header' 
    - label: 'Input'
      link: '/component/input'
    - label: 'List'
      link: '/component/list'
    - label: 'Modal'
      link: '/component/modal'
    - label: 'Navbar'
      link: '/component/navbar'
    - label: 'Toolbar'
      link: '/component/toolbar'  
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/bothelljs/core
